/* 
 * Ducksms
 *
 * Ducksms is a leading SMS messaging service provider offering one-way SMS communication services from your internet enabled computer. The API allow you to directly communicate and manage a SMS with our SMS gateway system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Org.Ducksms.Client;
using Org.Ducksms.Model;

namespace Org.Ducksms.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICreditApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Credit Balance
        /// </summary>
        /// <remarks>
        /// Get available credit balance
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>CreditBalance</returns>
        CreditBalance CreditBalance ();

        /// <summary>
        /// Credit Balance
        /// </summary>
        /// <remarks>
        /// Get available credit balance
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of CreditBalance</returns>
        ApiResponse<CreditBalance> CreditBalanceWithHttpInfo ();
        /// <summary>
        /// Credit History
        /// </summary>
        /// <remarks>
        /// Get all credit history
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterType">Filter by credit type (optional)</param>
        /// <param name="filterSmsSmsid">Filter by sms id (optional)</param>
        /// <returns>CreditHistory</returns>
        CreditHistory CreditHistory (int? page = default(int?), string filterType = default(string), int? filterSmsSmsid = default(int?));

        /// <summary>
        /// Credit History
        /// </summary>
        /// <remarks>
        /// Get all credit history
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterType">Filter by credit type (optional)</param>
        /// <param name="filterSmsSmsid">Filter by sms id (optional)</param>
        /// <returns>ApiResponse of CreditHistory</returns>
        ApiResponse<CreditHistory> CreditHistoryWithHttpInfo (int? page = default(int?), string filterType = default(string), int? filterSmsSmsid = default(int?));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Credit Balance
        /// </summary>
        /// <remarks>
        /// Get available credit balance
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of CreditBalance</returns>
        System.Threading.Tasks.Task<CreditBalance> CreditBalanceAsync ();

        /// <summary>
        /// Credit Balance
        /// </summary>
        /// <remarks>
        /// Get available credit balance
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (CreditBalance)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreditBalance>> CreditBalanceAsyncWithHttpInfo ();
        /// <summary>
        /// Credit History
        /// </summary>
        /// <remarks>
        /// Get all credit history
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterType">Filter by credit type (optional)</param>
        /// <param name="filterSmsSmsid">Filter by sms id (optional)</param>
        /// <returns>Task of CreditHistory</returns>
        System.Threading.Tasks.Task<CreditHistory> CreditHistoryAsync (int? page = default(int?), string filterType = default(string), int? filterSmsSmsid = default(int?));

        /// <summary>
        /// Credit History
        /// </summary>
        /// <remarks>
        /// Get all credit history
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterType">Filter by credit type (optional)</param>
        /// <param name="filterSmsSmsid">Filter by sms id (optional)</param>
        /// <returns>Task of ApiResponse (CreditHistory)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreditHistory>> CreditHistoryAsyncWithHttpInfo (int? page = default(int?), string filterType = default(string), int? filterSmsSmsid = default(int?));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CreditApi : ICreditApi
    {
        private Org.Ducksms.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CreditApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CreditApi(String basePath)
        {
            this.Configuration = new Org.Ducksms.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Org.Ducksms.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreditApi"/> class
        /// </summary>
        /// <returns></returns>
        public CreditApi()
        {
            this.Configuration = Org.Ducksms.Client.Configuration.Default;

            ExceptionFactory = Org.Ducksms.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreditApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CreditApi(Org.Ducksms.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Org.Ducksms.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Org.Ducksms.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.Ducksms.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.Ducksms.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Credit Balance Get available credit balance
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>CreditBalance</returns>
        public CreditBalance CreditBalance ()
        {
             ApiResponse<CreditBalance> localVarResponse = CreditBalanceWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Credit Balance Get available credit balance
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of CreditBalance</returns>
        public ApiResponse<CreditBalance> CreditBalanceWithHttpInfo ()
        {

            var localVarPath = "/api/v1/credits/balance";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (BearerToken) required
            // http beerer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreditBalance", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreditBalance>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreditBalance) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreditBalance)));
        }

        /// <summary>
        /// Credit Balance Get available credit balance
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of CreditBalance</returns>
        public async System.Threading.Tasks.Task<CreditBalance> CreditBalanceAsync ()
        {
             ApiResponse<CreditBalance> localVarResponse = await CreditBalanceAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Credit Balance Get available credit balance
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (CreditBalance)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CreditBalance>> CreditBalanceAsyncWithHttpInfo ()
        {

            var localVarPath = "/api/v1/credits/balance";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (BearerToken) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreditBalance", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreditBalance>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreditBalance) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreditBalance)));
        }

        /// <summary>
        /// Credit History Get all credit history
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterType">Filter by credit type (optional)</param>
        /// <param name="filterSmsSmsid">Filter by sms id (optional)</param>
        /// <returns>CreditHistory</returns>
        public CreditHistory CreditHistory (int? page = default(int?), string filterType = default(string), int? filterSmsSmsid = default(int?))
        {
             ApiResponse<CreditHistory> localVarResponse = CreditHistoryWithHttpInfo(page, filterType, filterSmsSmsid);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Credit History Get all credit history
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterType">Filter by credit type (optional)</param>
        /// <param name="filterSmsSmsid">Filter by sms id (optional)</param>
        /// <returns>ApiResponse of CreditHistory</returns>
        public ApiResponse<CreditHistory> CreditHistoryWithHttpInfo (int? page = default(int?), string filterType = default(string), int? filterSmsSmsid = default(int?))
        {

            var localVarPath = "/api/v1/credits/history";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (filterType != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter[type]", filterType)); // query parameter
            if (filterSmsSmsid != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter[sms.smsid]", filterSmsSmsid)); // query parameter

            // authentication (BearerToken) required
            // http beerer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreditHistory", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreditHistory>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreditHistory) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreditHistory)));
        }

        /// <summary>
        /// Credit History Get all credit history
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterType">Filter by credit type (optional)</param>
        /// <param name="filterSmsSmsid">Filter by sms id (optional)</param>
        /// <returns>Task of CreditHistory</returns>
        public async System.Threading.Tasks.Task<CreditHistory> CreditHistoryAsync (int? page = default(int?), string filterType = default(string), int? filterSmsSmsid = default(int?))
        {
             ApiResponse<CreditHistory> localVarResponse = await CreditHistoryAsyncWithHttpInfo(page, filterType, filterSmsSmsid);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Credit History Get all credit history
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterType">Filter by credit type (optional)</param>
        /// <param name="filterSmsSmsid">Filter by sms id (optional)</param>
        /// <returns>Task of ApiResponse (CreditHistory)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CreditHistory>> CreditHistoryAsyncWithHttpInfo (int? page = default(int?), string filterType = default(string), int? filterSmsSmsid = default(int?))
        {

            var localVarPath = "/api/v1/credits/history";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (filterType != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter[type]", filterType)); // query parameter
            if (filterSmsSmsid != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter[sms.smsid]", filterSmsSmsid)); // query parameter

            // authentication (BearerToken) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreditHistory", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreditHistory>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreditHistory) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreditHistory)));
        }

    }
}
