/* 
 * Ducksms
 *
 * Ducksms is a leading SMS messaging service provider offering one-way SMS communication services from your internet enabled computer. The API allow you to directly communicate and manage a SMS with our SMS gateway system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Org.Ducksms.Client;
using Org.Ducksms.Model;

namespace Org.Ducksms.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISmsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Send Sms
        /// </summary>
        /// <remarks>
        /// Create a new sms
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSchema">Create a new sms (optional)</param>
        /// <returns>PreviewSmsSend</returns>
        PreviewSmsSend SmsSend (SmsSchema smsSchema = default(SmsSchema));

        /// <summary>
        /// Send Sms
        /// </summary>
        /// <remarks>
        /// Create a new sms
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSchema">Create a new sms (optional)</param>
        /// <returns>ApiResponse of PreviewSmsSend</returns>
        ApiResponse<PreviewSmsSend> SmsSendWithHttpInfo (SmsSchema smsSchema = default(SmsSchema));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Send Sms
        /// </summary>
        /// <remarks>
        /// Create a new sms
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSchema">Create a new sms (optional)</param>
        /// <returns>Task of PreviewSmsSend</returns>
        System.Threading.Tasks.Task<PreviewSmsSend> SmsSendAsync (SmsSchema smsSchema = default(SmsSchema));

        /// <summary>
        /// Send Sms
        /// </summary>
        /// <remarks>
        /// Create a new sms
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSchema">Create a new sms (optional)</param>
        /// <returns>Task of ApiResponse (PreviewSmsSend)</returns>
        System.Threading.Tasks.Task<ApiResponse<PreviewSmsSend>> SmsSendAsyncWithHttpInfo (SmsSchema smsSchema = default(SmsSchema));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SmsApi : ISmsApi
    {
        private Org.Ducksms.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SmsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SmsApi(String basePath)
        {
            this.Configuration = new Org.Ducksms.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Org.Ducksms.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SmsApi"/> class
        /// </summary>
        /// <returns></returns>
        public SmsApi()
        {
            this.Configuration = Org.Ducksms.Client.Configuration.Default;

            ExceptionFactory = Org.Ducksms.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SmsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SmsApi(Org.Ducksms.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Org.Ducksms.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Org.Ducksms.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.Ducksms.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.Ducksms.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Send Sms Create a new sms
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSchema">Create a new sms (optional)</param>
        /// <returns>PreviewSmsSend</returns>
        public PreviewSmsSend SmsSend (SmsSchema smsSchema = default(SmsSchema))
        {
             ApiResponse<PreviewSmsSend> localVarResponse = SmsSendWithHttpInfo(smsSchema);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Send Sms Create a new sms
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSchema">Create a new sms (optional)</param>
        /// <returns>ApiResponse of PreviewSmsSend</returns>
        public ApiResponse<PreviewSmsSend> SmsSendWithHttpInfo (SmsSchema smsSchema = default(SmsSchema))
        {

            var localVarPath = "/api/v1/sms/send";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (smsSchema != null && smsSchema.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(smsSchema); // http body (model) parameter
            }
            else
            {
                localVarPostBody = smsSchema; // byte array
            }

            // authentication (BearerToken) required
            // http beerer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SmsSend", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PreviewSmsSend>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (PreviewSmsSend) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PreviewSmsSend)));
        }

        /// <summary>
        /// Send Sms Create a new sms
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSchema">Create a new sms (optional)</param>
        /// <returns>Task of PreviewSmsSend</returns>
        public async System.Threading.Tasks.Task<PreviewSmsSend> SmsSendAsync (SmsSchema smsSchema = default(SmsSchema))
        {
             ApiResponse<PreviewSmsSend> localVarResponse = await SmsSendAsyncWithHttpInfo(smsSchema);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Send Sms Create a new sms
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="smsSchema">Create a new sms (optional)</param>
        /// <returns>Task of ApiResponse (PreviewSmsSend)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PreviewSmsSend>> SmsSendAsyncWithHttpInfo (SmsSchema smsSchema = default(SmsSchema))
        {

            var localVarPath = "/api/v1/sms/send";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (smsSchema != null && smsSchema.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(smsSchema); // http body (model) parameter
            }
            else
            {
                localVarPostBody = smsSchema; // byte array
            }

            // authentication (BearerToken) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SmsSend", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PreviewSmsSend>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (PreviewSmsSend) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PreviewSmsSend)));
        }

    }
}
