/* 
 * Ducksms
 *
 * Ducksms is a leading SMS messaging service provider offering one-way SMS communication services from your internet enabled computer. The API allow you to directly communicate and manage a SMS with our SMS gateway system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Org.Ducksms.Client;
using Org.Ducksms.Model;

namespace Org.Ducksms.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISmsScheduleApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Cancel Sms Schedule
        /// </summary>
        /// <remarks>
        /// Cancel existing sms schedule
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>CancelSmsSchedule</returns>
        CancelSmsSchedule CancelSmsSchedule (string id);

        /// <summary>
        /// Cancel Sms Schedule
        /// </summary>
        /// <remarks>
        /// Cancel existing sms schedule
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of CancelSmsSchedule</returns>
        ApiResponse<CancelSmsSchedule> CancelSmsScheduleWithHttpInfo (string id);
        /// <summary>
        /// List Sms Schedule
        /// </summary>
        /// <remarks>
        /// List all the sms schedule
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterSenderName">Filter by sender id name (optional)</param>
        /// <param name="filterType">Filter by sms type (optional)</param>
        /// <param name="filterMessageType">Filter by sms message type (optional)</param>
        /// <param name="filterStatus">Filter by sms status (optional)</param>
        /// <returns>ListSmsSchedule</returns>
        ListSmsSchedule ListSmsSchedule (int? page = default(int?), string filterSenderName = default(string), string filterType = default(string), string filterMessageType = default(string), string filterStatus = default(string));

        /// <summary>
        /// List Sms Schedule
        /// </summary>
        /// <remarks>
        /// List all the sms schedule
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterSenderName">Filter by sender id name (optional)</param>
        /// <param name="filterType">Filter by sms type (optional)</param>
        /// <param name="filterMessageType">Filter by sms message type (optional)</param>
        /// <param name="filterStatus">Filter by sms status (optional)</param>
        /// <returns>ApiResponse of ListSmsSchedule</returns>
        ApiResponse<ListSmsSchedule> ListSmsScheduleWithHttpInfo (int? page = default(int?), string filterSenderName = default(string), string filterType = default(string), string filterMessageType = default(string), string filterStatus = default(string));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Cancel Sms Schedule
        /// </summary>
        /// <remarks>
        /// Cancel existing sms schedule
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of CancelSmsSchedule</returns>
        System.Threading.Tasks.Task<CancelSmsSchedule> CancelSmsScheduleAsync (string id);

        /// <summary>
        /// Cancel Sms Schedule
        /// </summary>
        /// <remarks>
        /// Cancel existing sms schedule
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ApiResponse (CancelSmsSchedule)</returns>
        System.Threading.Tasks.Task<ApiResponse<CancelSmsSchedule>> CancelSmsScheduleAsyncWithHttpInfo (string id);
        /// <summary>
        /// List Sms Schedule
        /// </summary>
        /// <remarks>
        /// List all the sms schedule
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterSenderName">Filter by sender id name (optional)</param>
        /// <param name="filterType">Filter by sms type (optional)</param>
        /// <param name="filterMessageType">Filter by sms message type (optional)</param>
        /// <param name="filterStatus">Filter by sms status (optional)</param>
        /// <returns>Task of ListSmsSchedule</returns>
        System.Threading.Tasks.Task<ListSmsSchedule> ListSmsScheduleAsync (int? page = default(int?), string filterSenderName = default(string), string filterType = default(string), string filterMessageType = default(string), string filterStatus = default(string));

        /// <summary>
        /// List Sms Schedule
        /// </summary>
        /// <remarks>
        /// List all the sms schedule
        /// </remarks>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterSenderName">Filter by sender id name (optional)</param>
        /// <param name="filterType">Filter by sms type (optional)</param>
        /// <param name="filterMessageType">Filter by sms message type (optional)</param>
        /// <param name="filterStatus">Filter by sms status (optional)</param>
        /// <returns>Task of ApiResponse (ListSmsSchedule)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListSmsSchedule>> ListSmsScheduleAsyncWithHttpInfo (int? page = default(int?), string filterSenderName = default(string), string filterType = default(string), string filterMessageType = default(string), string filterStatus = default(string));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SmsScheduleApi : ISmsScheduleApi
    {
        private Org.Ducksms.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SmsScheduleApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SmsScheduleApi(String basePath)
        {
            this.Configuration = new Org.Ducksms.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Org.Ducksms.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SmsScheduleApi"/> class
        /// </summary>
        /// <returns></returns>
        public SmsScheduleApi()
        {
            this.Configuration = Org.Ducksms.Client.Configuration.Default;

            ExceptionFactory = Org.Ducksms.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SmsScheduleApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SmsScheduleApi(Org.Ducksms.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Org.Ducksms.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Org.Ducksms.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.Ducksms.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.Ducksms.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Cancel Sms Schedule Cancel existing sms schedule
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>CancelSmsSchedule</returns>
        public CancelSmsSchedule CancelSmsSchedule (string id)
        {
             ApiResponse<CancelSmsSchedule> localVarResponse = CancelSmsScheduleWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Cancel Sms Schedule Cancel existing sms schedule
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of CancelSmsSchedule</returns>
        public ApiResponse<CancelSmsSchedule> CancelSmsScheduleWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling SmsScheduleApi->CancelSmsSchedule");

            var localVarPath = "/api/v1/sms/scheduled/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (BearerToken) required
            // http beerer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CancelSmsSchedule", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CancelSmsSchedule>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CancelSmsSchedule) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CancelSmsSchedule)));
        }

        /// <summary>
        /// Cancel Sms Schedule Cancel existing sms schedule
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of CancelSmsSchedule</returns>
        public async System.Threading.Tasks.Task<CancelSmsSchedule> CancelSmsScheduleAsync (string id)
        {
             ApiResponse<CancelSmsSchedule> localVarResponse = await CancelSmsScheduleAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Cancel Sms Schedule Cancel existing sms schedule
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Task of ApiResponse (CancelSmsSchedule)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CancelSmsSchedule>> CancelSmsScheduleAsyncWithHttpInfo (string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling SmsScheduleApi->CancelSmsSchedule");

            var localVarPath = "/api/v1/sms/scheduled/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // authentication (BearerToken) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CancelSmsSchedule", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CancelSmsSchedule>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CancelSmsSchedule) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CancelSmsSchedule)));
        }

        /// <summary>
        /// List Sms Schedule List all the sms schedule
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterSenderName">Filter by sender id name (optional)</param>
        /// <param name="filterType">Filter by sms type (optional)</param>
        /// <param name="filterMessageType">Filter by sms message type (optional)</param>
        /// <param name="filterStatus">Filter by sms status (optional)</param>
        /// <returns>ListSmsSchedule</returns>
        public ListSmsSchedule ListSmsSchedule (int? page = default(int?), string filterSenderName = default(string), string filterType = default(string), string filterMessageType = default(string), string filterStatus = default(string))
        {
             ApiResponse<ListSmsSchedule> localVarResponse = ListSmsScheduleWithHttpInfo(page, filterSenderName, filterType, filterMessageType, filterStatus);
             return localVarResponse.Data;
        }

        /// <summary>
        /// List Sms Schedule List all the sms schedule
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterSenderName">Filter by sender id name (optional)</param>
        /// <param name="filterType">Filter by sms type (optional)</param>
        /// <param name="filterMessageType">Filter by sms message type (optional)</param>
        /// <param name="filterStatus">Filter by sms status (optional)</param>
        /// <returns>ApiResponse of ListSmsSchedule</returns>
        public ApiResponse<ListSmsSchedule> ListSmsScheduleWithHttpInfo (int? page = default(int?), string filterSenderName = default(string), string filterType = default(string), string filterMessageType = default(string), string filterStatus = default(string))
        {

            var localVarPath = "/api/v1/sms/scheduled";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (filterSenderName != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter[sender_name]", filterSenderName)); // query parameter
            if (filterType != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter[type]", filterType)); // query parameter
            if (filterMessageType != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter[message_type]", filterMessageType)); // query parameter
            if (filterStatus != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter[status]", filterStatus)); // query parameter

            // authentication (BearerToken) required
            // http beerer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListSmsSchedule", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListSmsSchedule>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ListSmsSchedule) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListSmsSchedule)));
        }

        /// <summary>
        /// List Sms Schedule List all the sms schedule
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterSenderName">Filter by sender id name (optional)</param>
        /// <param name="filterType">Filter by sms type (optional)</param>
        /// <param name="filterMessageType">Filter by sms message type (optional)</param>
        /// <param name="filterStatus">Filter by sms status (optional)</param>
        /// <returns>Task of ListSmsSchedule</returns>
        public async System.Threading.Tasks.Task<ListSmsSchedule> ListSmsScheduleAsync (int? page = default(int?), string filterSenderName = default(string), string filterType = default(string), string filterMessageType = default(string), string filterStatus = default(string))
        {
             ApiResponse<ListSmsSchedule> localVarResponse = await ListSmsScheduleAsyncWithHttpInfo(page, filterSenderName, filterType, filterMessageType, filterStatus);
             return localVarResponse.Data;

        }

        /// <summary>
        /// List Sms Schedule List all the sms schedule
        /// </summary>
        /// <exception cref="Org.Ducksms.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (optional)</param>
        /// <param name="filterSenderName">Filter by sender id name (optional)</param>
        /// <param name="filterType">Filter by sms type (optional)</param>
        /// <param name="filterMessageType">Filter by sms message type (optional)</param>
        /// <param name="filterStatus">Filter by sms status (optional)</param>
        /// <returns>Task of ApiResponse (ListSmsSchedule)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ListSmsSchedule>> ListSmsScheduleAsyncWithHttpInfo (int? page = default(int?), string filterSenderName = default(string), string filterType = default(string), string filterMessageType = default(string), string filterStatus = default(string))
        {

            var localVarPath = "/api/v1/sms/scheduled";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (page != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "page", page)); // query parameter
            if (filterSenderName != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter[sender_name]", filterSenderName)); // query parameter
            if (filterType != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter[type]", filterType)); // query parameter
            if (filterMessageType != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter[message_type]", filterMessageType)); // query parameter
            if (filterStatus != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "filter[status]", filterStatus)); // query parameter

            // authentication (BearerToken) required
            // http bearer authentication required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListSmsSchedule", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListSmsSchedule>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ListSmsSchedule) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListSmsSchedule)));
        }

    }
}
