/* 
 * Ducksms
 *
 * Ducksms is a leading SMS messaging service provider offering one-way SMS communication services from your internet enabled computer. The API allow you to directly communicate and manage a SMS with our SMS gateway system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.Ducksms.Client;
using Org.Ducksms.Api;
using Org.Ducksms.Model;

namespace Org.Ducksms.Test
{
    /// <summary>
    ///  Class for testing SmsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SmsApiTests
    {
        private SmsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SmsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SmsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' SmsApi
            //Assert.IsInstanceOf(typeof(SmsApi), instance);
        }

        
        /// <summary>
        /// Test SmsSend
        /// </summary>
        [Test]
        public void SmsSendTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SmsSchema smsSchema = null;
            //var response = instance.SmsSend(smsSchema);
            //Assert.IsInstanceOf(typeof(PreviewSmsSend), response, "response is PreviewSmsSend");
        }
        
    }

}
