/* 
 * Ducksms
 *
 * Ducksms is a leading SMS messaging service provider offering one-way SMS communication services from your internet enabled computer. The API allow you to directly communicate and manage a SMS with our SMS gateway system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.Ducksms.Client;
using Org.Ducksms.Api;
using Org.Ducksms.Model;

namespace Org.Ducksms.Test
{
    /// <summary>
    ///  Class for testing SmsScheduleApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SmsScheduleApiTests
    {
        private SmsScheduleApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SmsScheduleApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SmsScheduleApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' SmsScheduleApi
            //Assert.IsInstanceOf(typeof(SmsScheduleApi), instance);
        }

        
        /// <summary>
        /// Test CancelSmsSchedule
        /// </summary>
        [Test]
        public void CancelSmsScheduleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.CancelSmsSchedule(id);
            //Assert.IsInstanceOf(typeof(CancelSmsSchedule), response, "response is CancelSmsSchedule");
        }
        
        /// <summary>
        /// Test ListSmsSchedule
        /// </summary>
        [Test]
        public void ListSmsScheduleTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //string filterSenderName = null;
            //string filterType = null;
            //string filterMessageType = null;
            //string filterStatus = null;
            //var response = instance.ListSmsSchedule(page, filterSenderName, filterType, filterMessageType, filterStatus);
            //Assert.IsInstanceOf(typeof(ListSmsSchedule), response, "response is ListSmsSchedule");
        }
        
    }

}
