/* 
 * Ducksms
 *
 * Ducksms is a leading SMS messaging service provider offering one-way SMS communication services from your internet enabled computer. The API allow you to directly communicate and manage a SMS with our SMS gateway system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Ducksms.Api;
using Org.Ducksms.Model;
using Org.Ducksms.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Ducksms.Test
{
    /// <summary>
    ///  Class for testing ErrorUnauthenticated
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorUnauthenticatedTests
    {
        // TODO uncomment below to declare an instance variable for ErrorUnauthenticated
        //private ErrorUnauthenticated instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ErrorUnauthenticated
            //instance = new ErrorUnauthenticated();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ErrorUnauthenticated
        /// </summary>
        [Test]
        public void ErrorUnauthenticatedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ErrorUnauthenticated
            //Assert.IsInstanceOf(typeof(ErrorUnauthenticated), instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
