/* 
 * Ducksms
 *
 * Ducksms is a leading SMS messaging service provider offering one-way SMS communication services from your internet enabled computer. The API allow you to directly communicate and manage a SMS with our SMS gateway system.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ducksms.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Ducksms.Api;
using Org.Ducksms.Model;
using Org.Ducksms.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Ducksms.Test
{
    /// <summary>
    ///  Class for testing SmsSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SmsSchemaTests
    {
        // TODO uncomment below to declare an instance variable for SmsSchema
        //private SmsSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SmsSchema
            //instance = new SmsSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SmsSchema
        /// </summary>
        [Test]
        public void SmsSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SmsSchema
            //Assert.IsInstanceOf(typeof(SmsSchema), instance);
        }


        /// <summary>
        /// Test the property 'Preview'
        /// </summary>
        [Test]
        public void PreviewTest()
        {
            // TODO unit test for the property 'Preview'
        }
        /// <summary>
        /// Test the property 'MobileNumbers'
        /// </summary>
        [Test]
        public void MobileNumbersTest()
        {
            // TODO unit test for the property 'MobileNumbers'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'SenderId'
        /// </summary>
        [Test]
        public void SenderIdTest()
        {
            // TODO unit test for the property 'SenderId'
        }
        /// <summary>
        /// Test the property 'ScheduledAt'
        /// </summary>
        [Test]
        public void ScheduledAtTest()
        {
            // TODO unit test for the property 'ScheduledAt'
        }
        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Test]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }

    }

}
